### ISSUE TITLE
Dernière année manquante dans certains tableaux et graphes

### ISSUE THREAD

**Issue by ericjeangirard** [dataesr/scanr#179]
Il semble que les données de 2021 ne sont pas affichées dans l'encart publications (et je suppose projet).
Par ex sur la page https://scanr.enseignementsup-recherche.gouv.fr/person/idref122921941 , il devrait y avoir une publi en 2021, mais elle n'apparait pas dans le listing, ni dans la vue graphe "par année de publication"

**Comment by folland87** [comment]
Fait sur staging! Devrait etre visible à la prochaine release.
