### ISSUE TITLE
Export CSV fails

### ISSUE THREAD

**Issue by poplingue** [dataesr/scanr#196]
Zum Kolk, Caroline le mardi 21 septembre 2021 à 15:09:31
Nouveau
caroline.zumkolk@msh-paris.fr
Madame, Monsieur, cher.e collègue, Je souhaite vous signaler un problème rencontré suite à une recherche dans votre excellent et si utile moteur de recherche. Quand on exporte les résultats de la catégorie "Auteurs" d'une recherche, les liens qui figurent dans le fichier csv ("Lien vers fiche scanR" et "Contexte de recherche") provoquent une erreur 404 (objet introuvable). Exemple de lien vers la fiche scanR : https://scanr-api.enseignementsup-recherche.gouv.fr/person/idref151236054 Exemple de lien vers "Contexte de recherche" : https://scanr-api.enseignementsup-recherche.gouv.frscanr.esr.gouv.fr En vous remerciant par avance pour l'attention que vous voulez bien porter à ce signalement et bien cordialement, Caroline zum Kolk

**Comment by poplingue** [comment]
+  Et par la même occasion, supprimer le Genre de l''export en accord avec le front

**Comment by folland87** [comment]
résolu
