### ISSUE TITLE
Problem with the new certificate

### ISSUE THREAD

**Issue by charlycou** [dataesr/scanr#207]
Bonjour,
Je n'arrive plus à contacter l'API depuis l'émission du nouveau certificat (Thu, 13 Jan 2022 00:00:00 GMT). Dernier contact en succès le 11/01/22.
J'ai l'impression que la chaîne pem n'est pas complète et qu'il manque l'autorité de base 
```
openssl s_client -connect scanr-api.enseignementsup-recherche.gouv.fr:443
CONNECTED(00000003)
depth=0 C = FR, ST = \C3\8Ele-de-France, O = Minist\C3\A8re de l'Education Nationale et de la Jeunesse des sports, OU = DNE-PHE, CN = scanr-api.enseignementsup-recherche.gouv.fr
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = FR, ST = \C3\8Ele-de-France, O = Minist\C3\A8re de l'Education Nationale et de la Jeunesse des sports, OU = DNE-PHE, CN = scanr-api.enseignementsup-recherche.gouv.fr
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:C = FR, ST = \C3\8Ele-de-France, O = Minist\C3\A8re de l'Education Nationale et de la Jeunesse des sports, OU = DNE-PHE, CN = scanr-api.enseignementsup-recherche.gouv.fr
   i:C = NL, O = GEANT Vereniging, CN = GEANT OV RSA CA 4
---
```
Est-ce reproductible de votre côté?

**Comment by folland87** [comment]
Bonjour, 

Ca devrait être résolu. Pouvez-vous tester et me faire un retour ?

**Comment by charlycou** [comment]
https://scanr-api.enseignementsup-recherche.gouv.fr/api/v2/api-docs

**Comment by charlycou** [comment]
Bonjour,
Même problème que lors du précédent changement de certificat. Pouvez-vous positionner toute la chaîne de certificats avec les certificats des autorités de base ?
Beaucoup de librairies ne sont pas capables de faire de la résolution dynamique (à la différence des navigateurs) et on besoin des certificats de toute la chaîne d'autorité  pour interroger l'API.
Merci d'avance
