### ISSUE TITLE
Actualisation "partout" du nom d'auteur quand intervention sur nom d'auteur suite à demande utilisateur

### ISSUE THREAD

**Issue by Jojooct10** [dataesr/scanr#242]
exemple https://scanr.enseignementsup-recherche.gouv.fr/person/idref180556592
Le nom a été actualisé sur la page auteur mais la forme auteur liée à la thèse est restée sur la forme antérieure

**Comment by ericjeangirard** [comment]
Ce sera corrigé en prod au prochain déploiement
